export const START_LIST_LOAD = 'START_CASH_REGISTER_GROUP_SIMPLE_LIST_LOAD';
export const STOP_LIST_LOAD = 'STOP_CASH_REGISTER_GROUP_SIMPLE_LIST_LOAD';
export const UPDATE_LIST = 'UPDATE_CASH_REGISTER_GROUP_SIMPLE_LIST';