export const LOGIN = 'USER_LOGIN';
export const LOGOUT = 'USER_LOGOUT';
export const START_LOGIN_LOAD = 'START_LOGIN_LOAD';
export const STOP_LOGIN_LOAD = 'STOP_LOGIN_LOAD';
export const UPDATE_TOKEN = 'USER_UPDATE_TOKEN';
export const START_PROFILE_LOAD = 'START_PROFILE_LOAD';
export const STOP_PROFILE_LOAD = 'STOP_PROFILE_LOAD';
export const UPDATE_PROFILE = 'USER_UPDATE_PROFILE';