import Head from 'next/head'
import Image from 'next/image'
import React, { useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { Input, InputPassword } from '../components/input';
import { ButtonPrimary } from '../components/button';
import { UserOutlined } from '@ant-design/icons';
import { UserInterface } from '../store/user/model';
import { login } from '../store/user/actions';

export default function Home() {
  const [user, setUser] = useState('');
  const [password, setPassword] = useState('');

  const users = useSelector((state: { user: UserInterface }) => state.user)
  const dispatch = useDispatch();

  const handleLogin = () => {
    console.log('=>', user, password);

    dispatch(login({name: 'ste', token: ''}))
  }

  return (
    <div id="login-page">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {
          /* <h1>{users.name}</h1> */}
          <img src="/assets/images/logo_transparent.png" alt="Logo" />

          <strong>
            Seja bem vindo(a).
            <br />
            Insira seus dados e vamos começar.
          </strong>
          
          <form>
            <Input
              placeholder="Usuário ou email"
              value={user}
              onChange={e => setUser(e.target.value)}
              suffix={<UserOutlined/>}
            />
       
            <InputPassword
              placeholder="Senha"
              value={password}
              onChange={e => setPassword(e.target.value)}
            />

            <ButtonPrimary 
              onClick={handleLogin}
            >
              Entrar
            </ButtonPrimary>
          </form>
      </main>

      <footer>
        {/* <a
          href="welingtonfidelis.dev.br"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            Construido por Welington Fidelis de Sousa
          </span>
        </a> */}
      </footer>
    </div>
  )
}
