export const START_LIST_LOAD = 'START_CASH_REGISTER_LIST_LOAD';
export const STOP_LIST_LOAD = 'STOP_CASH_REGISTER_LIST_LOAD';
export const START_SAVE_LOAD = 'START_CASH_REGISTER_SAVE_LOAD';
export const STOP_SAVE_LOAD = 'STOP_CASH_REGISTER_SAVE_LOAD';
export const START_DELETE_LOAD = 'START_CASH_REGISTER_DELETE_LOAD';
export const STOP_DELETE_LOAD = 'STOP_CASH_REGISTER_DELETE_LOAD';
export const UPDATE_LIST = 'UPDATE_CASH_REGISTER_LIST';